name: default
channels:
  - defaults
dependencies:
  # - anaconda::jupyter=1.0.0
  - anaconda::numpy=1.26.0
  - anaconda::flake8=6.0.0

  # - conda-forge::conda=23.3.1
  - conda-forge::notebook=7.0.6
  - conda-forge::pip=23.1
  - conda-forge::black=23.10.1
  - conda-forge::black-jupyter=23.10.1
  - conda-forge::python-dotenv=1.0.0 
  - conda-forge::scipy=1.10.1
  - conda-forge::matplotlib=3.7.1
  - conda-forge::pytest=7.2.2
  - conda-forge::watchdog=3.0.0
