name: Build and push Docker images

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build-and-push-docker-images:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - dockerfile: src/Dockerfile.common.dev
            containerName: python-econ-devcontainer
            containerTag: 1.0.0
            username: econ
            environmentName: econ
            environmentConfig: ./src/econ/environment.econ.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.images.containerName }}:${{ matrix.images.containerTag }}
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ..
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.images.containerName }}:${{ matrix.images.containerTag }}
          file: ${{ matrix.images.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          build-args: |
            ROOT_PASS=${{ secrets.DOCKER_IMAGE_ROOT_PASS }}
            USERNAME=${{ matrix.images.username }}
            ENVIRONMENT_NAME=${{ matrix.images.environmentName }}
            ENVIRONMENT_CONFIG=${{ matrix.images.environmentConfig }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
